version: '3.2'
services:
  app:
    build: 
      context: auth-server/app
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/auth-server/app
      - /usr/src/auth-server/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start
  
  db:
    image: postgres:10.6
    restart: always
    container_name: auth_db
    environment:
    - POSTGRESQL_DATABASE=db
    - POSTGRESQL_USERNAME=postgres
    - POSTGRESQL_PASSWORD=postgres
    ports:
    - 5432:5432

